### ISSUE TITLE
en el perfil de Instituto Gobierno Fácil al ver el perfil público en convenios con empresas y dar clic sale este error 

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/vinculacion#101]
![captura de pantalla 2016-11-18 a la s 1 32 23 p m](https://cloud.githubusercontent.com/assets/2530269/20443724/a6410666-ad93-11e6-8fc7-26dfcbe4be65.png)

**Comment by hugovom** [comment]
esto es un error que viene de la carga de convenios al asignar empresa @CarlosOsorio
