### ISSUE TITLE
desde el administrador, cuando me voy a universidades y reviso el perfil del instituto gobierno fácil, y me voy a convenios y quiero editarlo sacar ese error 

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/vinculacion#102]
![captura de pantalla 2016-11-18 a la s 4 45 43 p m](https://cloud.githubusercontent.com/assets/2530269/20449377/806e4ed8-adae-11e6-842d-385961408ce8.png)

**Comment by hugovom** [comment]
@ArgentinaVelasco el error está en el convenio, se creó antes de la actualización a la db, lo mejor es que borres ese convenio y generes uno nuevo
