### ISSUE TITLE
Empresa/aplicante: Información del CV

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/vinculacion#50]

**Comment by elcoruco** [comment]
Lo apliqué en empresa -> ver candidato (falta lo de estudios, pero funciona igual):
<img width="699" alt="screen shot 2016-10-30 at 7 35 17 pm" src="https://cloud.githubusercontent.com/assets/3756555/19841897/1fc0e1d4-9ed8-11e6-9a46-cbda621784f6.png">

**Comment by hugovom** [comment]
@elcoruco tenemos algo para validar cuándo está completo?

**Comment by elcoruco** [comment]
@hugovom no, pero podemos inventarnos uno (solo es definir a qué le llamamos CV completo)

**Comment by hugovom** [comment]
pues cuando agregó: 
- datos personales
- Formación Académica
- Formación Complementaria
- Experiencia Profesional
