### ISSUE TITLE
Entradas sin usuarios

### ISSUE THREAD

**Issue by CarlosOsorio** [GobiernoFacil/vinculacion#70]
Al cargar estudiantes y/o empresas desde un excel o desde  administrador se crean entradas sin usuarios y se generan problemas al cargar los views para usuarios tipo universidad y empresas.  Además, ni universidades o el administrador puede asignar un usuario al estudiante.

**Comment by hugovom** [comment]
@elcoruco

**Comment by elcoruco** [comment]
Sí, solo cargan listas sin usuario. Solo existen usuarios para estudiante cuando el estudiante se registra (elige un correo y un pass). En los views que truena, hay que cambiar el enfoque de usuario a estudiante/empresa (es decir, se despliega la info del estudiante/empresa, y la info de usuario es un extra que solo ve el admin principal)
