### ISSUE TITLE
Cuando agendas una entrevista no respeta el formato del día

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/vinculacion#95]

**Comment by ArgentinaVelasco** [comment]
![captura de pantalla 2016-11-17 a la s 5 10 36 p m](https://cloud.githubusercontent.com/assets/2530269/20411819/d49f9050-ace8-11e6-98ac-78114c4896d7.png)

**Comment by hugovom** [comment]
no lo pude replicar
